site_name: AI Engineering Course
site_dir: build

nav:
  - Home: index.md
  - "Module 1":
    - Overview: Module-1/index.md
    - "Class 1: Python Data Types": Module-1/class-1-python-data-types.md
    - "Class 2: Python Fundamentals": Module-1/class-2-python-fundamentals.md

theme:
  name: material
  logo: assets/logo.svg
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - assets/js/external-links.js
